### ISSUE TITLE
Add check for user-agent

### ISSUE THREAD

**Issue by daniel-white** [terrycain/sanic-json-logging#38]
Using this in a microservice architecture, the `User-Agent` header is not always sent. The `JSONReqFormatter` has a hard coded expectation that `User-Agent` is in the request headers. So if `User-Agent` isn't passed it throws.

**Comment by terrycain** [comment]
Wow, someone other than me uses this :smile:.

Am patching now

**Comment by terrycain** [comment]
Fixed in 1.2.0
