### ISSUE TITLE
Example for accessing req_id within request?

### ISSUE THREAD

**Issue by abatilo** [terrycain/sanic-json-logging#49]
Hi there!

I'm wondering if there's a way to grab the request I'd within the context of a request handler. This would be great for being able to forward the request I'd, as I make requests to other services, so that I can follow the entire request trace path.

I tried looking through the req object that gets handed through to a handler, but I couldn't find the req_id anywhere.

Thanks!

**Comment by terrycain** [comment]
So the req_id is stored and propagated on the async task object, not in the request dictionary so that if you log in an async function inside the request handler, it still knows the request id.

```python
current_task = asyncio.Task.current_task()
if current_task and hasattr(current_task, 'context'):
    req_id = current_task.context['req_id']

# OR
req_id = getattr(asyncio.Task.current_task(), 'context', {}).get('req_id')  # Would be None if no req_id
```
I actually have #4 to keep reminding me to add req_id to the request dict.

**Comment by terrycain** [comment]
You should now be able to do `request['req_id']` in v1.3.0
