### ISSUE TITLE
AttributeError: 'str' object has no attribute 'headers' on every access log

### ISSUE THREAD

**Issue by madsenwattiq** [terrycain/sanic-json-logging#77]
Sanic version 19.6.2
Simple API app with GET methods, JSON responses
Default setup of sanic_json_logging.  

I get:  
--- Logging error ---

> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1025, in emit
>     msg = self.format(record)
>   File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 869, in format
>     return fmt.format(record)
>   File "/Users/mark/ibis/devel/src/publicapi-server/venv/lib/python3.7/site-packages/sanic_json_logging/formatters.py", line 167, in format
>     ip = record.request.headers.get('X-Forwarded-For', record.request.ip)
> AttributeError: 'str' object has no attribute 'headers'

on every request.  Am I running an incompatible version of Sanic?  Why would `record.request` be a string object in this case?  

Thanks - I've been wanting JSON access logs for AWS and Elasticsearch as well, appreciate you building a library for this!

**Comment by terrycain** [comment]
Sorry for the delay, record.request "should" be an object. Are you using the JSONReqFormatter to format normal log lines? How are you setting up logging in general? Are you using `setup_json_logging`?

**Comment by GitMastStas** [comment]
Hmm

**Comment by digitalkaoz** [comment]
got the same error while noticing it happens only on some requests:

faulty traceback (only the difference):

```
  File "sanic_plugin_toolkit/realm.py", line 550, in _handle_request_21_03
    _ = await real_handle(request)
  File "sanic/app.py", line 779, in handle_request
    await response.send(end_stream=True)
  File "sanic/response.py", line 122, in send
    await self.stream.send(data, end_stream=end_stream)
  File "sanic/http.py", line 348, in http1_response_header
    self.log_response()
  File "sanic/http.py", line 458, in log_response
    access_logger.info("", extra=extra)
```

working traceback:

```
  File "sanic_plugin_toolkit/realm.py", line 550, in _handle_request_21_03
    _ = await real_handle(request)
  File "sanic/app.py", line 773, in handle_request
    response = await request.respond(response)
  File "sanic/request.py", line 183, in respond
    response = await self.app._run_response_middleware(
  File "sanic_plugin_toolkit/realm.py", line 771, in _run_response_middleware_21_03
    _response = await _response
  File "sanic_json_logging/__init__.py", line 91, in log_json_post
    req_logger.info(
```

it seems to happen only on failing requests (raising an exception somewhere)

**Comment by digitalkaoz** [comment]
found it, the library seems incompatible with (the latest? version of sanic):

```python
#sanic/http.py 440

    def log_response(self) -> None:
        """
        Helper method provided to enable the logging of responses in case if
        the :attr:`HttpProtocol.access_log` is enabled.
        """
        req, res = self.request, self.response
        extra = {
            "status": getattr(res, "status", 0),
            "byte": getattr(
                self, "response_bytes_left", getattr(self, "response_size", -1)
            ),
            "host": "UNKNOWN",
            "request": "nil",
        }
        if req is not None:
            if req.ip:
                extra["host"] = f"{req.ip}:{req.port}"
            extra["request"] = f"{req.method} {req.url}"  # THATS THE LINE CAUSING THE ERROR
        access_logger.info("", extra=extra)

```

**Comment by digitalkaoz** [comment]
got it working by disabling access logs on the app instance itself.

what i am missing here is a proper exception handler (for logging exception as json aswell) @terrycain

**Comment by terrycain** [comment]
Ah, is entirely possible, i'll look into it.

**Comment by terrycain** [comment]
Ok so I managed to replicate this only if you use the `disable_json_access_log=True` flag, as then it doesn't run `app.config.ACCESS_LOG = False` which would disable the access log. 

The problem then comes from when that argument is set, it won't register a post request middleware to log out the access log but it will still assign the `JSONReqFormatter` to the `sanic.access` logger, which now won't log a line with extra info like request and response, only with the "extra" from that stacktrace.

v4.0.1 fixes this.

**Comment by digitalkaoz** [comment]
fixed by https://github.com/terrycain/sanic-json-logging/commit/985276ed8aaeb67acf237bb0af9ff571ee967a77

**Comment by terrycain** [comment]
v4.1.0 is out :smile:
